"use client";

import { useEffect, useState } from "react";
import type { GeneratedItem, McqOption } from "@/lib/types";

interface Topic {
  id: string;
  form: number;
  chapter: number;
  title: string;
  _count: { questions: number };
}
interface Subject {
  id: string;
  name: string;
  topics: Topic[];
}

export default function GeneratePage() {
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [subjectId, setSubjectId] = useState("");
  const [topicId, setTopicId] = useState("");
  const [type, setType] = useState("structured");
  const [count, setCount] = useState(3);
  const [kbat, setKbat] = useState(true);
  const [loading, setLoading] = useState(false);
  const [items, setItems] = useState<GeneratedItem[]>([]);
  const [byAi, setByAi] = useState(false);
  const [revealed, setRevealed] = useState<Set<number>>(new Set());

  useEffect(() => {
    fetch("/api/taxonomy")
      .then((r) => r.json())
      .then((data: Subject[]) => {
        setSubjects(data);
        if (data[0]) {
          setSubjectId(data[0].id);
          setTopicId(data[0].topics[0]?.id ?? "");
        }
      });
  }, []);

  const subject = subjects.find((s) => s.id === subjectId);

  async function generate() {
    if (!topicId) return;
    setLoading(true);
    setItems([]);
    setRevealed(new Set());
    const res = await fetch("/api/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ topicId, questionType: type, count, kbat }),
    });
    const data = await res.json();
    setItems(data.generated?.map(toItem) ?? []);
    setByAi(data.byAi);
    setLoading(false);
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">AI Question Generator ✨</h1>
        <p className="text-sm text-slate-500">
          Create fresh practice questions in the style of real SPM past papers — including KBAT.
        </p>
      </div>

      <div className="card grid gap-4 p-5 sm:grid-cols-2">
        <div>
          <label className="label">Subject</label>
          <select
            className="input"
            value={subjectId}
            onChange={(e) => {
              setSubjectId(e.target.value);
              const s = subjects.find((x) => x.id === e.target.value);
              setTopicId(s?.topics[0]?.id ?? "");
            }}
          >
            {subjects.map((s) => (
              <option key={s.id} value={s.id}>{s.name}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Topic</label>
          <select className="input" value={topicId} onChange={(e) => setTopicId(e.target.value)}>
            {subject?.topics.map((t) => (
              <option key={t.id} value={t.id}>
                T{t.form} · Bab {t.chapter} · {t.title} ({t._count.questions})
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Type</label>
          <select className="input" value={type} onChange={(e) => setType(e.target.value)}>
            <option value="mcq">Objektif (MCQ)</option>
            <option value="structured">Struktur</option>
            <option value="essay">Esei</option>
          </select>
        </div>
        <div>
          <label className="label">How many</label>
          <input
            type="number"
            min={1}
            max={8}
            className="input"
            value={count}
            onChange={(e) => setCount(Number(e.target.value))}
          />
        </div>
        <label className="flex items-center gap-2 text-sm font-medium sm:col-span-2">
          <input type="checkbox" checked={kbat} onChange={(e) => setKbat(e.target.checked)} className="h-4 w-4" />
          KBAT (higher-order thinking)
        </label>
        <div className="sm:col-span-2">
          <button onClick={generate} disabled={loading || !topicId} className="btn-primary w-full sm:w-auto">
            {loading ? "Generating…" : "Generate questions"}
          </button>
        </div>
      </div>

      {items.length > 0 && (
        <section className="space-y-3">
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-500">
              {items.length} generated
            </h2>
            <span className={`badge ${byAi ? "bg-accent-100 text-accent-700" : "bg-slate-200 text-slate-600"}`}>
              {byAi ? "Generated by AI" : "Offline samples"}
            </span>
            <span className="badge bg-emerald-100 text-emerald-700">✓ Saved to Practice</span>
          </div>
          {items.map((q, i) => (
            <div key={i} className="card p-4">
              <div className="mb-2 flex flex-wrap items-center gap-2">
                <span className="badge bg-slate-100 text-slate-600">{q.questionType}</span>
                <span className="badge bg-slate-100 text-slate-600">{q.marks} markah</span>
                {q.isKbat && <span className="tag-kbat">KBAT</span>}
              </div>
              <p className="whitespace-pre-wrap font-medium">{q.stem}</p>
              {q.options && q.options.length > 0 && (
                <ul className="mt-2 space-y-1 text-sm">
                  {q.options.map((o) => (
                    <li key={o.key}>
                      <span className="font-semibold">{o.key}.</span> {o.text}
                    </li>
                  ))}
                </ul>
              )}
              <div className="mt-3 flex items-center gap-4">
                <button
                  className="text-sm font-semibold text-brand-600 hover:underline"
                  onClick={() =>
                    setRevealed((prev) => {
                      const n = new Set(prev);
                      n.has(i) ? n.delete(i) : n.add(i);
                      return n;
                    })
                  }
                >
                  {revealed.has(i) ? "Hide answer" : "Show answer & scheme"}
                </button>
                {q.id && (
                  <a href={`/practice/${q.id}`} className="text-sm font-semibold text-emerald-700 hover:underline">
                    Attempt &amp; get graded →
                  </a>
                )}
              </div>
              {revealed.has(i) && (
                <div className="mt-2 space-y-2 rounded-xl bg-slate-50 p-3 text-sm">
                  {q.answer && (
                    <p><span className="font-semibold">Answer: </span>{q.answer}</p>
                  )}
                  {q.markingScheme && (
                    <p><span className="font-semibold">Scheme: </span>{q.markingScheme}</p>
                  )}
                  {q.basedOn && <p className="text-xs text-slate-400">{q.basedOn}</p>}
                </div>
              )}
            </div>
          ))}
        </section>
      )}
    </div>
  );
}

// The API persists generated rows with options as JSON strings; normalise here.
function toItem(g: {
  id?: string;
  questionType: string;
  stem: string;
  options: string;
  answer: string | null;
  markingScheme: string | null;
  marks: number;
  isKbat: boolean;
  basedOn: string | null;
}): GeneratedItem {
  let options: McqOption[] = [];
  try {
    options = JSON.parse(g.options || "[]");
  } catch {
    options = [];
  }
  return {
    id: g.id,
    questionType: g.questionType as GeneratedItem["questionType"],
    stem: g.stem,
    options,
    answer: g.answer ?? undefined,
    markingScheme: g.markingScheme ?? undefined,
    marks: g.marks,
    isKbat: g.isKbat,
    basedOn: g.basedOn ?? undefined,
  };
}
